version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:58a345bc2dbafed28c2deb5096dc8cb6c4a11958da9d890c02f5a3d870eef836
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.6-alpine@sha256:a546d6c5f530bbcc2d41fbf0da21d94da9f70cba2997c82b57b06ea6a2ef155d
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"